apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
    labels:
        argocd.argoproj.io/instance: controlplane-prod-external-secrets
    name: "controlplane-prod"
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        key: ca.crt
        name: bitwarden-tls-certs
        namespace: external-secrets
        type: Secret
      identityURL: https://vault.bitwarden.com/identity
      organizationID: af3fe9e1-e0bc-4f66-9b6d-b3ce0108febb
      projectID: 1c2eb3f1-360d-4267-89b4-b3ef002896bb

